#SPDX-License-Identifier: MIT-0
---
# 03-build file for fortune-mod

- name: Create build directory
  ansible.builtin.file:
    path: "{{ build_dir }}"
    state: directory

- name: Build
  shell: >
    cmake .. &&
    make &&
    make install
  args:
    chdir: "{{ build_dir }}"
